# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIn2KEP6kONgNafP4RdE_nOoNfB-S7Gd

## Tasks 1 and 2(Ingestion and Cleaning)
Task 01: Write explicit StructType schemas for all 4 CSVs. Load them with header=True but no inferSchema. Any row that fails casting goes into a "rejected Dataframe which you log separately.
"""

from pyspark.sql import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import *
spark = SparkSession.builder.getOrCreate()

customerStruct = StructType([
    StructField('customer_id', StringType(), True),
    StructField('customer_name', StringType(), True),
    StructField('email', StringType(), True),
    StructField('country', StringType(), True),
    StructField('customer_tier', StringType(), True),
    StructField('signup_date', StringType(), True),
])

df_customers = spark.read.format('csv')\
                .schema(customerStruct)\
                .option('inferschema', False)\
                .option('header', True)\
                .load('C:/Users/ADMIN/Desktop/Lux Dev Data Enginering/Assignment_1/data/customers.csv')

val = [df_customers.collect()[0]["signup_date"]]
print(val)
formatted_date = []

# Check if the date value is not None before processing
if val[0] is not None and '/' in val[0]:
    year = val[0][6:10]
    month = val[0][3:5]
    day = val[0][0:2]
    new_date = f'{year}-{month}-{day}'
    print(new_date)
    formatted_date.append(new_date)
else:
    # Handle the case when date is None or doesn't contain '/'
    if val[0] is not None:
        formatted_date.append(val[0])  # Keep original format if no '/'
    else:
        formatted_date.append("No date available")  # Handle None case

print(formatted_date)

df_customers.show()

df_customers.printSchema()

orderItemStruct = StructType([
    StructField('item_id', StringType(), True),
    StructField('order_id', StringType(), True),
    StructField('product_name', StringType(), True),
    StructField('category', StringType(), True),
    StructField('quantity', IntegerType(), True),
    StructField('unit_price', FloatType(), True),
])

df_order_items = spark.read.format('csv')\
                .schema(orderItemStruct)\
                .option('inferschema', False)\
                .option('header', True)\
                .load('C:/Users/ADMIN/Desktop/Lux Dev Data Enginering/Assignment_1/data/order_items.csv')

df_order_items.show()

df_order_items.printSchema()

orderStruct = StructType([
    StructField("order_id", StringType(), True),
    StructField("customer_id", StringType(), True),
    StructField("order_date", StringType(), True),
    StructField("status", StringType(), True),
    StructField("total_amount", FloatType(), True),
    StructField("discount_pct",IntegerType(), True)
    ])

df_orders = spark.read.format('csv')\
                .schema(orderStruct)\
                .option('inferschema', False)\
                .option('header', True)\
                .load('C:/Users/ADMIN/Desktop/Lux Dev Data Enginering/Assignment_1/data/orders.csv')
df_orders.show()

df_orders.printSchema()

returnStruct = StructType ([
    StructField('return_id', StringType(), True),
    StructField('order_id', StringType(), True),
    StructField('return_date', StringType(), True),
    StructField('reason', StringType(), True),
    StructField('refund_amount', FloatType(), True)
])

df_returns = spark.read.format('csv')\
                .schema(returnStruct)\
                .option('inferschema', False)\
                .option('header', True)\
                .load('C:/Users/ADMIN/Desktop/Lux Dev Data Enginering/Assignment_1/data/returns.csv')
df_returns.show()

df_returns.printSchema()

"""Task 02: Clean in the exact sequence the spec says deduplicate-> normalize dates -> lowercase tier -> drop nulls -> flag negatives. Handling the mixed date formats(year-month-day vs day-month-year). use F.to/-date with coalesce to try both formats."""

# Remove exact duplicate rows using dropDuplicates().
df_customers = df_customers.dropDuplicates()
df_order_items = df_order_items.dropDuplicates()
df_returns = df_returns.dropDuplicates()
df_orders = df_orders.dropDuplicates()

df_customers = df_customers.withColumn(
    'signup_date',
    coalesce(
        try_to_date(col("signup_date"), "yyyy-MM-dd"),
        try_to_date(col("signup_date"), "dd/MM/yyyy")
    )
)

df_customers.show()

df_orders = df_orders.withColumn(
    'order_date',
    coalesce(
        try_to_date(col("order_date"), "yyyy-MM-dd"),
        try_to_date(col("order_date"), "dd/MM/yyyy")
    )
  )
df_orders.show()

## Standardise customer_tier to lowercase.
df_customers = df_customers.withColumn("customer_tier", lower("customer_tier"))
df_customers.show()

## Drop rows where order_id or customer_id is NULL.
df_customers = df_customers.dropna(subset=["customer_id"])
df_order_items = df_order_items.dropna(subset=["order_id"])
df_returns = df_returns.dropna(subset=["order_id"])
df_orders = df_orders.dropna(subset=["order_id", "customer_id"])
df_customers.show()

## Add a boolean column is_negative_amount to flag (not drop) orders with total_amount < 0.
df_orders = df_orders.withColumn("is_negative_amount", when((col('total_amount') < 0), "True").otherwise("False"))
df_orders.show()

"""## Task 03 and 04
### Joins + Aggregations

Task 03: Three joins - orders-> customers(inner), orders->order_items(left), then an anti-join to catch orphaned itens. Derive net_amount as a new column
"""

df_order_customer= df_orders.join(df_customers, on=["customer_id"], how="inner")

df_order_customer.show()

df_orders_order_items = df_orders.join(df_order_items, on=["order_id"], how="left")
df_orders_order_items.show()

df_orphaned_order_items = df_orders.join(df_order_items, on=["order_id"], how="anti")
df_orphaned_order_items.show()

df_orphaned_customers = df_orders.join(df_customers, on=["customer_id"], how="anti")
df_orphaned_customers.show()

# Add a derived column net_amount = total_amount × (1 − discount_pct / 100)
df_order_customer = df_order_customer.withColumn('net_amount', (col("total_amount") * (1 - col("discount_pct")/100)))
df_order_customer.show()

"""### Task 4 - Three window function outputs. partitionBy and orderBy for each - rank by country, rolling 7-day count, monthly revenue share per category."""

#  Customers ranked by lifetime net spend within each country.
## columns to use - net_amount, country, customer_id

from pyspark.sql.window import Window
from pyspark.sql import functions as F

windowSpec = Window.partitionBy("customer_name").orderBy(F.desc("net_amount"))

# 1. Aggregate to calculate total lifetime spend per customer per country
df_lifetime = df_order_customer.groupBy("country", "customer_id", "customer_name") \
                .agg(F.sum("net_amount").alias("lifetime_net_spend"))

# 2. Define the Window to rank by spend within each country
# Highest spend gets rank 1
window_spec = Window.partitionBy("country").orderBy(F.col("lifetime_net_spend").desc())

# 3. Apply dense_rank() to handle potential spending ties gracefully
df_ranked = df_lifetime.withColumn("spend_rank", F.dense_rank().over(window_spec))

# Display the final ranking
df_ranked.orderBy("country", "spend_rank").show()

# A 7-day rolling order count per customer (based on order_date).

df_oc = df_order_customer.withColumn("date_in_seconds", F.col("order_date").cast("timestamp").cast("long"))

seconds_in_7_days = 6 * 24 * 60 * 60

window_spec = Window.partitionBy("customer_id") \
                    .orderBy("date_in_seconds") \
                    .rangeBetween(-seconds_in_7_days, Window.currentRow)

df_rolling = df_oc.withColumn(
    "rolling_7day_order_count",
    F.count("order_id").over(window_spec)
).drop("date_in_seconds")

df_rolling.orderBy("customer_id", "order_date").show()

# Each product category’s share of total revenue per calendar month.
df_prod_cat = df_orders_order_items.groupBy("category", "order_date").agg(F.sum("total_amount").alias("total_revenue"))

# 3. Define a Window partitioned ONLY by month to sum up all categories together
monthly_window = Window.partitionBy("order_date")

# 4. Calculate the total monthly revenue and divide the category share
df_share = df_prod_cat \
    .withColumn("total_monthly_revenue", F.sum("total_revenue").over(monthly_window)) \
    .withColumn("revenue_share_pct", F.round((F.col("total_revenue") / F.col("total_monthly_revenue")) * 100, 2))

# Display the result sorted chronologically
df_share.orderBy("order_date", F.col("revenue_share_pct").desc()).show()

## Join returns to your enriched orders DataFrame
df_order_customer = df_order_customer.join(df_ranked, on=["customer_id"], how="inner")
df_order_customer.show(10)

df_orders_order_items.show(5)

## Compute return rates using groupBy aggregations
df_return_rates = df_orders_order_items.groupBy("category").agg(
    # 1. Total orders in this category
    F.count("order_id").alias("total_orders"),

    # 2. Returned orders — no .otherwise() so non-matches become NULL and count skips them
    F.count(
        F.when(F.col("status") == "refunded", F.col("order_id"))
    ).alias("total_returned")

).withColumn(
    # 3. Return rate percentage
    "return_rate_pct",
    F.round((F.col("total_returned") / F.col("total_orders")) * 100, 2)
)

df_return_rates.orderBy(F.col("return_rate_pct").desc()).show()

## Flag where refund_amount > net_amount

## Get top 10 refund customers

df_order_customer = df_order_customer.drop("country", "customer_name")  # drop one of the duplicates

df_order_customer.write \
    .mode('overwrite') \
    .parquet('C:/Users/ADMIN/Desktop/Assignment_1/')

## writing summary tables to csv
df_return_rates.write('csv')\
    .mode('overwrite')\
    .option('path', 'C:/Users/ADMIN/Desktop/Assignment_1/output/return_rates.csv')\
    .save()

## writing summary tables to csv
df_share.write('csv')\
    .mode('overwrite')\
    .option('path', 'C:\Users\ADMIN\Desktop\Lux Dev Data Enginering\Assignment_1\pc_share.csv')\
    .save()